.TH FLIDGET_NET_LOAD 1
.SH NAME
flidget_net_load \- script that periodically polls network load.
.SH SYNOPSIS
.B flidget_net_load
net_device integration_time
.SH OPTIONS
.TP
.BR net_device
Network device to monitor (e.g: eth0).
.TP
.BR integration_time
floating point decimal with the integration time in seconds (e.g. 1.0).
