.TH FLIDGET_CPU_TEMP 1
.SH NAME
flidget_cpu_temp \- script that periodically polls CPU temperature.
.SH SYNOPSIS
.B flidget_cpu_temp
cpu_core refresh_period
.SH OPTIONS
.TP
.BR cpu_core
Real core number. Starts at 0.
.TP
.BR refresh_period
floating point decimal with the refresh period seconds (e.g. 1.0).
